version: "3.4"

services:
  webserver:
    image: opencve:latest
    container_name: opencve-webserver
    build:
      context: ./opencve-docker
      args:
        - OPENCVE_REPOSITORY=https://github.com/opencve/opencve.git
        - OPENCVE_VERSION=1.5.0
    depends_on:
      - postgres-opencve
      - redis-opencve
    command: webserver -b 0.0.0.0:8000 --env SCRIPT_NAME=/opencve
    environment:
      - SCRIPT_NAME=/opencve
    volumes:
      - ./opencve_data/conf/opencve.cfg:/app/opencve.cfg:ro
    ports:
      - "8000:8000"
    restart: unless-stopped

  celery_beat:
    image: opencve:latest
    container_name: opencve-celery-beat
    depends_on:
      - webserver
      - redis-opencve
    entrypoint: ["/bin/sh", "-c", "rm -f /app/celerybeat.pid /tmp/celerybeat.pid && exec ./run.sh celery-beat"]
    volumes:
      - ./opencve_data/conf/opencve.cfg:/app/opencve.cfg:ro
    restart: unless-stopped

  celery_worker:
    image: opencve:latest
    container_name: opencve-celery-worker
    depends_on:
      - webserver
      - redis-opencve
    command: celery-worker
    volumes:
      - ./opencve_data/conf/opencve.cfg:/app/opencve.cfg:ro
    restart: unless-stopped

  redis-opencve:
    container_name: redis-opencve
    image: redis:buster
    restart: unless-stopped

  postgres-opencve:
    container_name: postgres-opencve
    image: postgres:11
    environment:
      POSTGRES_USER: opencve
      POSTGRES_PASSWORD: opencvepassword
      POSTGRES_DB: opencve
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./opencve_data/db:/var/lib/postgresql/data
    restart: unless-stopped
